Repository openworm/geppetto-client, pull requests merged in 2019-11, with the labels that each got.

#104 Tree Browser improvements
  js/components/interface/controlPanel/controlpanel.js
  js/components/interface/moviePlayer/MoviePlayer.js
  js/components/interface/tree/Tree.js
  js/components/interface/tutorial/Tutorial.js
Labels: bug, enhancement

#118 stackviewer bug on reopening fixed
  js/components/widgets/stackViewer/StackViewerComponent.js
Labels: bug

#117 tooltip re-alignment between buttonbar, focusterm and other components
  js/components/widgets/popup/ButtonBarComponent.js
Labels: enhancement

#147 #126 graph visualization collide radius
  js/components/interface/graph-visualization/Graph.js
  js/components/interface/graph-visualization/utils.js
  js/components/interface/listViewer/PopupColorPicker.js
Labels: enhancement
