Repository openworm/geppetto-client, pull requests merged in 2019-07, with the labels that each got.

#22 Feature new query builder
  js/components/ComponentFactory.js
  js/components/interface/3dCanvas/ThreeDEngine.js
  js/components/interface/query/customComponents/queryLinkComponent.js
  js/components/interface/query/customComponents/queryResultsControlsComponent.js
  js/components/interface/query/customComponents/slideshowImageComponent.js
  js/components/interface/query/queryBuilder.js
  js/components/interface/query/queryFooter.js
  js/components/interface/query/queryItem.js
  js/components/interface/spotlight/spotlight.js
Labels: enhancement

#40 Trigger Python command exec error event
  js/communication/geppettoJupyter/GeppettoJupyterUtils.js
  js/pages/geppetto/GEPPETTO.Events.js
Labels: feature

#57 quoting fields in CSV
  js/components/interface/query/queryBuilder.js
Labels: bug
