Repository openworm/geppetto-client, pull requests merged in 2020-05, with the labels that each got.

#188 Feature/489
  js/components/interface/query/customComponents/slideshowImageComponent.js
  js/components/interface/query/query.less
  js/components/widgets/stackViewer/StackViewerComponent.js
Labels: enhancement, ready for review

#183 Frontend websocket reconnection
  js/common/GEPPETTO.Resources.js
  js/communication/GEPPETTO.GlobalHandler.js
  js/communication/MessageHandler.js
  js/communication/MessageSocket.js
Labels: bug, enhancement, ready for review

#180 Fix/179 Scaling image requests to > or match display scaling and support for hide/show layers
  js/components/widgets/stackViewer/StackViewerComponent.js
Labels: enhancement, feature, ready for review

#248 #247 fix underscore version for patch release
  package-lock.json
  package.json
Labels: bug, ready for review

#211 Feature/204
  js/components/interface/3dCanvas/Canvas.js
  js/components/interface/3dCanvas/ThreeDEngine.js
  js/pages/geppetto/GEPPETTO.Events.js
Labels: bug, ready for review

#249 Feature/234
  js/components/interface/graph-visualization/Graph.js
  package.json
Labels: enhancement

#264 #263 Fix python controlled capability calling setState on unMounted c…
  js/communication/geppettoJupyter/PythonControlledCapability.js
Labels: :bug: Bug
