Repository openworm/geppetto-client, pull requests merged in 2020-06, with the labels that each got.

#260 #232 onLoad method for canvas plus small improvements to animation
  js/components/interface/3dCanvas/Canvas.js
  js/components/interface/3dCanvas/ThreeDEngine.js
  js/geppettoModel/ModelFactory.js
  js/pages/geppetto/GEPPETTO.Events.js
Labels: enhancement

#275 #274 uppercase typo in the socketStatus
  js/communication/GEPPETTO.GlobalHandler.js
Labels: :bug: Bug

#265 Add controls to Tree component
  js/components/interface/tree/Tree.js
Labels: enhancement

#301 Movie filter optional for geppetto canvas
  js/components/interface/3dCanvas/Canvas.js
  js/components/interface/3dCanvas/ThreeDEngine.js
Labels: enhancement

#291 fix/290 performance improvements for Stack Viewer
  js/components/widgets/stackViewer/StackViewerComponent.js
  style/css/gpt-icons.css
  style/fonts/gpt-icons.eot
  style/fonts/gpt-icons.svg
  style/fonts/gpt-icons.ttf
  style/fonts/gpt-icons.woff
  style/fonts/gpt-icons.woff2
Labels: ready for review
